-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 19:54:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema softrh2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softrh2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softrh2` DEFAULT CHARACTER SET utf8 ;
USE `softrh2` ;

-- -----------------------------------------------------
-- Table `softrh2`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh2`.`Service` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `nom_service` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh2`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh2`.`Employe` (
  `id_Employe` INT NOT NULL AUTO_INCREMENT,
  `utilisateur` VARCHAR(20) NOT NULL,
  `mdp` VARCHAR(20) NOT NULL,
  `admin` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_Employe`),
  UNIQUE INDEX `utilisateur_UNIQUE` (`utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh2`.`Humeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh2`.`Humeur` (
  `id_humeur` INT NOT NULL AUTO_INCREMENT,
  `nom_humeur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_humeur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh2`.`Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh2`.`Vote` (
  `id_vote` INT NOT NULL AUTO_INCREMENT,
  `id_humeur` INT NOT NULL,
  `id_service` INT NOT NULL,
  `vote_date` DATE NOT NULL,
  PRIMARY KEY (`id_vote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh2`.`has_voted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh2`.`has_voted` (
  `id_has_voted` INT NOT NULL AUTO_INCREMENT,
  `id_employe` INT NOT NULL,
  `vote_date` DATE NULL,
  PRIMARY KEY (`id_has_voted`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
