-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 15:52:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema softrh-test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softrh-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softrh-test` DEFAULT CHARACTER SET utf8 ;
USE `softrh-test` ;

-- -----------------------------------------------------
-- Table `softrh-test`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh-test`.`Service` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `nom_service` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh-test`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh-test`.`Employe` (
  `id_Employe` INT NOT NULL AUTO_INCREMENT,
  `utilisateur` VARCHAR(20) NOT NULL,
  `mdp` VARCHAR(20) NOT NULL,
  `admin` VARCHAR(5) NOT NULL,
  `Service_id_service` INT NOT NULL,
  PRIMARY KEY (`id_Employe`),
  UNIQUE INDEX `utilisateur_UNIQUE` (`utilisateur` ASC),
  INDEX `fk_Employe_Service_idx` (`Service_id_service` ASC),
  CONSTRAINT `fk_Employe_Service`
    FOREIGN KEY (`Service_id_service`)
    REFERENCES `softrh-test`.`Service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softrh-test`.`Humeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softrh-test`.`Humeur` (
  `id_humeur` INT NOT NULL AUTO_INCREMENT,
  `nom_humeur` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `Service_id_service` INT NOT NULL,
  PRIMARY KEY (`id_humeur`),
  INDEX `fk_Humeur_Service1_idx` (`Service_id_service` ASC),
  CONSTRAINT `fk_Humeur_Service1`
    FOREIGN KEY (`Service_id_service`)
    REFERENCES `softrh-test`.`Service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
